#!/usr/bin/env node
/**
 * write-config.mjs
 * Reads environment variables (optionally from a local .env file) and writes
 * a browser-loadable config.js that exposes runtime defaults to the app via
 * `window.METABOT_CONFIG`. Real process.env always wins over .env file values.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

/* Minimal zero-dependency .env loader. process.env takes precedence. */
function loadDotEnv() {
  const envPath = join(root, '.env');
  if (!existsSync(envPath)) return;
  for (const line of readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const m = trimmed.match(/^([\w.-]+)\s*=\s*(.*)$/);
    if (!m) continue;
    const key = m[1];
    const val = m[2].trim().replace(/^['"]|['"]$/g, '');
    if (process.env[key] === undefined) process.env[key] = val;
  }
}

const truthy = v => /^(1|true|yes|on)$/i.test((v || '').trim());
const numOrNull = v => (v != null && v !== '' && !Number.isNaN(Number(v)) ? Number(v) : null);

loadDotEnv();

const config = {
  rpcUrl:     process.env.DEFAULT_RPC_URL || '',
  maxGasGwei: numOrNull(process.env.DEFAULT_MAX_GAS_GWEI),
  tipGwei:    numOrNull(process.env.DEFAULT_TIP_GWEI),
  turboMode:  truthy(process.env.TURBO_MODE_ENABLED)
};

const out =
`/* AUTO-GENERATED by scripts/write-config.mjs — do not edit by hand. */
window.METABOT_CONFIG = ${JSON.stringify(config, null, 2)};
`;

const outPath = join(root, 'config.js');
writeFileSync(outPath, out);
console.log('Wrote', outPath);
console.log(config);
